È importante analizzare la natura del plagio del codice sorgente, distinguendolo dal plagio testuale e classificando le diverse strategie utilizzate per occultare il riutilizzo non autorizzato di codice.
== Cos'è il Plagio Software
Il plagio del codice sorgente è definito come l'atto di riutilizzare frammenti di codice altrui senza autorizzazione o attribuzione, presentandoli come propri. Nel contesto accademico è utilizzato come mezzo per ottenere vantaggi valutativi, ostacolando l'acquisizione di competenze logiche. Nel contesto professionale invece, si presenta spesso come una violazione delle licenze software e diritti di proprietà intellettuale.

A differenza dei contenuti testuali, il codice ha una struttura sintattica rigida e una semantica operativa. Gli strumenti di rilevazione devono essere "consapevoli" del linguaggio di programmazione per distinguere tra boilerplate code (codice standard necessario) e logica originale @plagDetectionSurvey. L'integrazione di risorse come Stack Overflow e repository open source ha reso i confini dell'utilizzo lecito sempre più sfumati, complicando ulteriormente la rilevazione del plagio @ref4.
== Tassonomia del plagio nel codice sorgente
Per analizzare il fenomeno, è utile classificare il plagio in base al livello di modifica apportato al codice originale. Una tassonomia efficace, supportata da *Hage et al. (2010)* @ref5 e *Prado et al. (2019)* @ref6 prevede quattro livelli crescenti di complessità:
- *Plagio Letterale (Verbatim)*: Copia esatta del file. Le uniche modifiche riguardano elementi non funzionali come spazi bianchi o commenti.
- *Plagio Superficiale (Shallow)*: Include ridenominazione sistematica di variabili e il cambiamento dell'ordine di dichiarazioni che non influenzano il flusso del programma.
- *Plagio Strutturale*: Comporta una modifica della logica di controllo, come la trasformazione di un ciclo `for` in un ciclo `while`, o l'estrazione di blocchi di codice in funzioni separate.
- *Plagio Semantico/Logico*: La riscrittura completa dell'algoritmo. Il comportamento osservabile rimane identico, ma la forma cambia radicalmente (es. passare da una funzione iterativa a una ricorsiva).

Nella letteratura sui code clones [13], questa tassonomia viene frequentemente espressa attraverso una notazione numerica equivalente: il plagio letterale corrisponde al *Tipo 1*, quello superficiale al *Tipo 2*, quello strutturale al *Tipo 3* e quello semantico al *Tipo 4*. Nel seguito del presente lavoro le due nomenclature verranno utilizzate in modo intercambiabile, privilegiando la notazione numerica nelle analisi comparative.
== Livelli e tecniche di offuscamento
L'offuscamento è l'applicazione intenzionale di trasformazioni per rendere il codice difficile da comprendere per gli esseri umani e difficile da analizzare per gli strumenti automatici.
=== Offuscamento lessicale e sintattico
L'offuscamento lessicale agisce sulla superficie testuale del programma, cercando di nascondere l'origine del codice attraverso modifiche formali che non toccano la logica interna. Una delle strategie più diffuse è lo *scrambling*, ovvero la ridenominazione degli identificatori, in cui nomi di variabili, funzioni e classi vengono sostituiti con nomi casuali o privi di senso, rendendo la lettura del codice difficile per un operatore umano.

A questa pratica si affianca spesso l'inserimento di "codice morto": si tratta di istruzioni sintatticamente corrette ma funzionalmente irrilevanti, inserite al solo scopo di "sporcare" l'impronta digitale del file e ingannare gli algoritmi di confronto. Sebbene questi attacchi mettano seriamente in crisi approcci di confronto testuale puro (string-based), essi risultano spesso inefficaci contro i sistemi basati su token, i quali, durante la fase di normalizzazione, eliminano commenti, spazi e nomi degli identificatori per concentrarsi sulla struttura dei tipi di istruzione.
=== Offuscamento strutturale
Un livello di manipolazione più avanzato mira a nascondere la gerarchia ed il flusso di esecuzione del programma attraverso trasformazioni strutturali. Tecniche comuni includono l'*inlining* e l'*outlining* delle funzioni: nel primo caso, il corpo di una funzione viene espanso direttamente nel punto di chiamata; nel secondo, un blocco di codice coerente viene estratto e trasformato in un metodo separato per frammentare la logica originale.

Un'altra strategia frequente consiste nel riodino dei blocchi di codice indipendenti o nel cambiamento nella posizione di attributi e metodi all'interno delle classi. Poichè tali modifiche alterano profondamente l'ordine sequenziale delle istruzioni, esse richiedono strumenti di rilevazione capaci di costruire e confrontare rappresentazioni astratte, come gli alberi sintattici (AST) o i grafi delle chiamate (call-graphs), che sono intrinsicamente più robusti rispetto alla semplice disposizione di blocchi di testo.
=== Offuscamento semantico e refactoring avanzato
L'offuscamento semantico rappresenta la sfida più complessa per i sistemi di SCPD, poiché sfrutta la conoscenza del dominio per riscrivere la logica stessa dell'algoritmo. In questo ambito, il plagiatore può optare per la sostituzione delle strutture dati, ad esempio rimpiazzando un array statico con una lista concatenata o una struttura dinamica equivalente, alterando così i pattern di accesso alla memoria ed i profili di esecuzione.

Queste tecniche di refactoring avanzato mirano a produrre versioni del software che, pur mantenendo lo stesso comportamento osservabile (input e output identici), appaiono radicalmente diverse davanti ad un'analisi statica. La letteratura evidenzia come la robustezza degli strumenti accademici o commerciali (come MOSS e JPLAG) debba essere costantemente testata contro tali trasformazioni. In particolare, con l'introduzione di strumenti come *COAT* (Code ObfuscAtion Tool) @ref7, progettato specificamente per generare varianti offuscate e valutare se i sistemi di rilevazione siano in grado di identificare la similarità semantica sottostante anche a fronte di cambiamenti logici significativi.