== Contesto e Motivazione
Negli ultimi decenni, lo sviluppo del software è diventato una componente ubiqua e critica in quasi ogni settore industriale e accademico. Parallelamente alla crescita della domanda di software, si è assistito a un aumento esponenziale dell'educazione informatica e delle risorse disponibili online, tra cui repository open source come GitHub e forum come Stack Overflow. Più recentemente, la diffusione di strumenti di AI generativa (come GitHub Copilot e i modelli della famiglia GPT) ha ulteriormente abbassato la soglia di accesso alla produzione di codice, introducendo nuove forme di riutilizzo non autorizzato che sfuggono ai paradigmi classici del plagio. Questo scenario ha reso il codice sorgente una risorsa estremamente accessibile, facilitando tuttavia pratiche scorrette come il plagio del codice sorgente (_Source Code Plagiarism_).

Le conseguenze di questa pratica si manifestano su due fronti distinti. In ambito accademico, il plagio mina l'integrità del processo valutativo e ostacola l'apprendimento degli studenti, che non acquisiscono le competenze logiche necessarie @jplagFinding. In ambito industriale, il riutilizzo non autorizzato di codice protetto da copyright solleva gravi questioni legali legate alla proprietà intellettuale e alla violazione delle licenze software. La rilevazione manuale di questi casi è diventata un compito impraticabile a causa della vastità dei dati da analizzare, rendendo lo sviluppo di strumenti automatizzati per la *Source Code Plagiarism Detection* (SCPD) un campo di ricerca attivo e necessario.

== Definizione del problema
Il plagio del codice sorgente consiste nel riutilizzo non autorizzato di frammenti di codice altrui, presentandoli come propri senza adeguata attribuzione @cosmaLSA. A differenza del plagio testuale, il codice possiede una struttura sintattica rigida e una semantica operativa: gli strumenti di rilevazione devono essere consapevoli del linguaggio di programmazione per distinguere tra _boilerplate code_ (codice standard necessario) e logica originale. Questo rende il problema intrinsecamente più complesso rispetto al confronto tra testi in linguaggio naturale.

Un'ulteriore difficoltà risiede nel fenomeno dell'offuscamento: chi plagia può applicare trasformazioni sistematiche al codice originale (dalla semplice ridenominazione delle variabili fino alla riscrittura completa dell'algoritmo) per mascherare l'origine del materiale e sfuggire ai controlli automatici. La tassonomia di queste trasformazioni e le tecniche per contrastarle costituiscono il nucleo del presente studio, approfondito nelle sezioni 2 e 3.
== Obiettivi dello studio
Questo studio mira a fornire una rassegna sistematica e aggiornata sullo stato dell'arte degli strumenti e delle tecniche per la rilevazione del plagio del codice sorgente (SCPD), identificando i metodi principali e le loro limitazioni. Gli obiettivi specifici includono:
- *Rassegna delle Tecniche*: Catalogare approcci teorici (string-based, tree-based, graph-based, learning-based) e valutarne efficacia contro varianti offuscate e codice AI-generato
- *Analisi Strumenti*: Esaminare tool open-source (es. JPlag, Dolos) e commerciali, producendo tabelle comparative su supporto linguaggi, accuratezza e usabilità
- *Valutazione Metodologica*: Definire metriche (precision, recall, robustness) e dataset standard, identificando sfide emergenti come il plagio cross-language e da IA generativa